// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var $$double = Caml_int32.imul;

exports.$$double = $$double;
/* No side effect */
