// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Sample$MyFirstApp = require("./Helpers/Sample.bs.js");
var Messages$MyFirstApp = require("./Messages.bs.js");

console.log(Messages$MyFirstApp.msg);

console.log(Sample$MyFirstApp.$$double(3, 4));

/*  Not a pure module */
